# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 25e88d5e0a58b7f4b7d912ea76587ed856972a97ce5395ee125262a0efe95202a07d9216545b467397acab3e5720ac88b3f4d3896923065cd09b469de5b541dd

test:
  secret_key_base: 3ddb2116e6cedf7b3a3f098e656e70ca1b7eabd08ed4bd8639867cb5ffd65068e468f8d788cff656c21500c30081ad71635d9d271f6ada80b0ef932d2314f8c7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
